# Pandas Library

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\mati\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mati\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
# Series — single labeled column
scores = pd.Series([88, 92, 79, 95],index=["Ali","Sara","Bilal","Hina"], name="Math_Score")

In [4]:
print(scores)

Ali      88
Sara     92
Bilal    79
Hina     95
Name: Math_Score, dtype: int64

In [5]:
# DataFrame — full student record
df = pd.DataFrame({
    "student":       ["Ali","Sara","Bilal","Hina"],
    "Math_Score":    [88, 92, 79, 95],
    "Science_Score": [75, 89, 91, 84],
    "Grade":         [9, 10, 9, 11]
})

In [6]:
print(df)

  student  Math_Score  Science_Score  Grade
0     Ali          88             75      9
1    Sara          92             89     10
2   Bilal          79             91      9
3    Hina          95             84     11

In [10]:
print(df['Math_Score'].median())

90.0

In [11]:
print(79+95)

174

In [12]:
print(174/2)

87.0

In [16]:
df=pd.read_csv('./heart-disease.csv')

In [17]:
print(df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]

In [22]:
# Add a column, then export cleanly
df["male"] = df["sex"] > 0

In [26]:
# Read a local CSV file correctly
pd.read_csv('./heart-disease.csv').head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
# Single condition
males = df[df["sex"] > 0]

In [28]:
males

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,male
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,True
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,True
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,True
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1,True
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0,True
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0,True
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0,True
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,True
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0,True

In [29]:
old= males[df['age']>50]

C:\Users\Mati\AppData\Local\Temp\ipykernel_7920\1472314839.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  old= males[df['age']>50]

In [30]:
old

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,male
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,True
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,True
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1,True
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1,True
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0,True
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0,True
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0,True
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,True
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0,True