# Pandas Practise

In [1]:
students=['ali','hamza','jamal']

In [2]:
students

['ali', 'hamza', 'jamal']

In [3]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\mati\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mati\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mati\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [5]:
recipes = pd.Series(
    ['biryani','qorma','pizza'],
    index=['Ali','Ahmed','Rizwan'],
    name='recipes'
)

In [6]:
recipes

Ali       biryani
Ahmed       qorma
Rizwan      pizza
Name: recipes, dtype: object

In [7]:
data_frame=pd.DataFrame({
    'names':['ali','ahmed','bilal'],
    'marks':[89,90,67],
    'grade':['B','A','C']
})

In [8]:
print(data_frame)

   names  marks grade
0    ali     89     B
1  ahmed     90     A
2  bilal     67     C

In [11]:
print(data_frame['marks'].mean())

82.0

In [12]:
print(data_frame['marks'].max())

90

In [13]:
print(data_frame['marks'].count())

3

In [15]:
print(data_frame['marks'].value_counts())

marks
89    1
90    1
67    1
Name: count, dtype: int64

In [17]:
diseases=pd.read_csv('./heart-disease.csv')

In [18]:
diseases

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [24]:
print(diseases.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0
1   37    1   2       130   250    0        1      187      0      3.5      0
2   41    0   1       130   204    0        0      172      0      1.4      2
3   56    1   1       120   236    0        1      178      0      0.8      2
4   57    0   0       120   354    0        1      163      1      0.6      2

   ca  thal  target
0   0     1       1
1   0     2       1
2   0     2       1
3   0     2       1
4   0     2       1

In [28]:
pd.read_excel('./tes.xlsx',sheet_name="Grades")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,"Schedule - ""B"""
0,NaN,Grades for Evaluation,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,GRADE,NaN,NaN,EXPLANATION,Score
3,NaN,5,Outstanding (OS),A,Performance consistently exceeds the required ...,80% and above
4,NaN,4,Exceeding Expectations (EE),B,Performance is well above the required standar...,70-79%
5,NaN,3,Meeting Expectations (ME),C,Performance is consistent & meets the required...,60-69%
6,NaN,2,Below Expectations (BE),D,Performance is inconsistent & behavior sometim...,50-59%
7,NaN,1,Serious Deficiencies,E,Performance falls below expectations on critic...,49% and below

In [30]:
data_frame.to_csv("marks.csv", index=True)